language: go
go:
  - "1.11"
  - "1.11.x"
env:
  - GO111MODULE=on
notifications:
  email:
    recipients:
      - wuxiaoshen@shu.edu.cn
    on_success: change # default: change
    on_failure: always # default: always


before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


script: true

after_success:
  - docker build . -t wuxiaoshen/beeQuick:latest -F Chapter5/BeeQuick.v1/deployments/Dockerfile
  - docker push wuxiaoshen/beeQuick:latest
