language: go
go:
  - "1.12"
  - "1.12.x"
env:
  - GO111MODULE=on
notifications:
  email:
    recipients:
      - wuxiaoshen@shu.edu.cn
    on_success: change # default: change
    on_failure: always # default: always


before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


script:
  - echo "Hello"
  - go fmt $(go list ./... | grep -v vendor)
  - go vet $(go list ./... | grep -v vendor)
  - make fmt
  - make vet
  - make

after_success:
  - docker build . -t wuxiaoshen/beequick:latest -f Chapter5/BeeQuick.v1/deployments/Dockerfile
  - docker build . -t wuxiaoshen/votes:latest -f chapter11/deployments/Dockerfile
  - docker build . -t wuxiaoshen/fina:latest -f chapter12/fina/deployments/Dockerfile
  - docker push wuxiaoshen/beequick:latest
  - docker push wuxiaoshen/votes:latest
  - docker push wuxiaoshen/fina:latest

# travis 是外国的服务商，无需设置 GOPROXY ，下载依赖没问题