language: go
go:
  - "1.12"
  - "1.12.x"
env:
  - GO111MODULE=on
notifications:
  email:
    recipients:
      - wuxiaoshen@shu.edu.cn
    on_success: change # default: change
    on_failure: always # default: always


before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


script:
  - cd chapter11 && echo "Hello"

after_success:
  - docker build . -t wuxiaoshen/beequick:latest -F Chapter5/BeeQuick.v1/deployments/Dockerfile
  - docker build . -t wuxiaoshen/votes:lates -F chapter11/deployments/Dockerfile
  - docker push wuxiaoshen/beequick:latest
  - docker push wuxiaoshen/votes:latest
