name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Go fmt
      run: go fmt $(go list ./... | grep -v vendor)
    - name: Make
      run: make
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file chapter10/BeeQuick.v1/deployments/Dockerfile --tag wuxiaoshen/beequick:v$(date +"%Y%m%d")
    - name: Build In Local
      run: cd chapter10/BeeQuick.v1 && docker build . --file Dockerfile --tag wuxiaoshen/beequick_local:v$(date +"%Y%m%d")